// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enter_room.proto

#ifndef PROTOBUF_enter_5froom_2eproto__INCLUDED
#define PROTOBUF_enter_5froom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "player.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enter_5froom_2eproto();
void protobuf_AssignDesc_enter_5froom_2eproto();
void protobuf_ShutdownFile_enter_5froom_2eproto();

class BINEnterRoomRequest;
class BINEnterRoomResponse;

// ===================================================================

class BINEnterRoomRequest : public ::google::protobuf::Message {
 public:
  BINEnterRoomRequest();
  virtual ~BINEnterRoomRequest();

  BINEnterRoomRequest(const BINEnterRoomRequest& from);

  inline BINEnterRoomRequest& operator=(const BINEnterRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINEnterRoomRequest& default_instance();

  void Swap(BINEnterRoomRequest* other);

  // implements Message ----------------------------------------------

  BINEnterRoomRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINEnterRoomRequest& from);
  void MergeFrom(const BINEnterRoomRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roomIndex = 1;
  inline bool has_roomindex() const;
  inline void clear_roomindex();
  static const int kRoomIndexFieldNumber = 1;
  inline ::google::protobuf::int32 roomindex() const;
  inline void set_roomindex(::google::protobuf::int32 value);

  // required bool vipRoom = 2;
  inline bool has_viproom() const;
  inline void clear_viproom();
  static const int kVipRoomFieldNumber = 2;
  inline bool viproom() const;
  inline void set_viproom(bool value);

  // optional string password = 3;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 3;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:BINEnterRoomRequest)
 private:
  inline void set_has_roomindex();
  inline void clear_has_roomindex();
  inline void set_has_viproom();
  inline void clear_has_viproom();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roomindex_;
  bool viproom_;
  ::std::string* password_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_enter_5froom_2eproto();
  friend void protobuf_AssignDesc_enter_5froom_2eproto();
  friend void protobuf_ShutdownFile_enter_5froom_2eproto();

  void InitAsDefaultInstance();
  static BINEnterRoomRequest* default_instance_;
};
// -------------------------------------------------------------------

class BINEnterRoomResponse : public ::google::protobuf::Message {
 public:
  BINEnterRoomResponse();
  virtual ~BINEnterRoomResponse();

  BINEnterRoomResponse(const BINEnterRoomResponse& from);

  inline BINEnterRoomResponse& operator=(const BINEnterRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINEnterRoomResponse& default_instance();

  void Swap(BINEnterRoomResponse* other);

  // implements Message ----------------------------------------------

  BINEnterRoomResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINEnterRoomResponse& from);
  void MergeFrom(const BINEnterRoomResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline bool responsecode() const;
  inline void set_responsecode(bool value);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // repeated .BINPlayer currentPlayers = 3;
  inline int currentplayers_size() const;
  inline void clear_currentplayers();
  static const int kCurrentPlayersFieldNumber = 3;
  inline const ::BINPlayer& currentplayers(int index) const;
  inline ::BINPlayer* mutable_currentplayers(int index);
  inline ::BINPlayer* add_currentplayers();
  inline const ::google::protobuf::RepeatedPtrField< ::BINPlayer >&
      currentplayers() const;
  inline ::google::protobuf::RepeatedPtrField< ::BINPlayer >*
      mutable_currentplayers();

  // @@protoc_insertion_point(class_scope:BINEnterRoomResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;
  ::google::protobuf::RepeatedPtrField< ::BINPlayer > currentplayers_;
  bool responsecode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_enter_5froom_2eproto();
  friend void protobuf_AssignDesc_enter_5froom_2eproto();
  friend void protobuf_ShutdownFile_enter_5froom_2eproto();

  void InitAsDefaultInstance();
  static BINEnterRoomResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BINEnterRoomRequest

// required int32 roomIndex = 1;
inline bool BINEnterRoomRequest::has_roomindex() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINEnterRoomRequest::set_has_roomindex() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINEnterRoomRequest::clear_has_roomindex() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINEnterRoomRequest::clear_roomindex() {
  roomindex_ = 0;
  clear_has_roomindex();
}
inline ::google::protobuf::int32 BINEnterRoomRequest::roomindex() const {
  return roomindex_;
}
inline void BINEnterRoomRequest::set_roomindex(::google::protobuf::int32 value) {
  set_has_roomindex();
  roomindex_ = value;
}

// required bool vipRoom = 2;
inline bool BINEnterRoomRequest::has_viproom() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINEnterRoomRequest::set_has_viproom() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINEnterRoomRequest::clear_has_viproom() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINEnterRoomRequest::clear_viproom() {
  viproom_ = false;
  clear_has_viproom();
}
inline bool BINEnterRoomRequest::viproom() const {
  return viproom_;
}
inline void BINEnterRoomRequest::set_viproom(bool value) {
  set_has_viproom();
  viproom_ = value;
}

// optional string password = 3;
inline bool BINEnterRoomRequest::has_password() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BINEnterRoomRequest::set_has_password() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BINEnterRoomRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BINEnterRoomRequest::clear_password() {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& BINEnterRoomRequest::password() const {
  return *password_;
}
inline void BINEnterRoomRequest::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void BINEnterRoomRequest::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void BINEnterRoomRequest::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINEnterRoomRequest::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  return password_;
}
inline ::std::string* BINEnterRoomRequest::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINEnterRoomRequest::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// BINEnterRoomResponse

// required bool responseCode = 1;
inline bool BINEnterRoomResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINEnterRoomResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINEnterRoomResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINEnterRoomResponse::clear_responsecode() {
  responsecode_ = false;
  clear_has_responsecode();
}
inline bool BINEnterRoomResponse::responsecode() const {
  return responsecode_;
}
inline void BINEnterRoomResponse::set_responsecode(bool value) {
  set_has_responsecode();
  responsecode_ = value;
}

// optional string message = 2;
inline bool BINEnterRoomResponse::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINEnterRoomResponse::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINEnterRoomResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINEnterRoomResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& BINEnterRoomResponse::message() const {
  return *message_;
}
inline void BINEnterRoomResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINEnterRoomResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINEnterRoomResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINEnterRoomResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* BINEnterRoomResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINEnterRoomResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .BINPlayer currentPlayers = 3;
inline int BINEnterRoomResponse::currentplayers_size() const {
  return currentplayers_.size();
}
inline void BINEnterRoomResponse::clear_currentplayers() {
  currentplayers_.Clear();
}
inline const ::BINPlayer& BINEnterRoomResponse::currentplayers(int index) const {
  return currentplayers_.Get(index);
}
inline ::BINPlayer* BINEnterRoomResponse::mutable_currentplayers(int index) {
  return currentplayers_.Mutable(index);
}
inline ::BINPlayer* BINEnterRoomResponse::add_currentplayers() {
  return currentplayers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BINPlayer >&
BINEnterRoomResponse::currentplayers() const {
  return currentplayers_;
}
inline ::google::protobuf::RepeatedPtrField< ::BINPlayer >*
BINEnterRoomResponse::mutable_currentplayers() {
  return &currentplayers_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enter_5froom_2eproto__INCLUDED
